Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -41,19 +41,29 @@ jobs:
     - name: Build Tests
       run: dotnet build --no-restore
       working-directory: TestNinja.UnitTests
-    #- name: Create Test Results folder
-      #run: mkdir TestResults
-    - name: Run Unit Test      
-      run: dotnet test --logger "trx;LogFileName=test-results.trx"
-    - name: Copy Unit Test Results
-      run: mkdir TestResults; cp TestNinja.UnitTests/TestResults/*.trx TestResults/
-      shell: bash
+    #- name: Run Unit Test      
+      #run: dotnet test --logger "trx;LogFileName=test-results.trx"
+    #- name: Copy Unit Test Results
+      #run: mkdir TestResults; cp TestNinja.UnitTests/TestResults/*.trx TestResults/
+      #shell: bash
+    #- name: Test Report
+      #uses: dorny/test-reporter@v1
+      #if: success() || failure()
+      #with:
+        #name: Test Results
+        #path: TestResults/*.trx
+        #reporter: dotnet-trx
+
+    - name: Run Unit Test
+      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
+      
     - name: Test Report
       uses: dorny/test-reporter@v1
-      if: success() || failure()
+      if: always()
       with:
-        name: Test Results
-        path: TestResults/*.trx
+        name: DotNET Tests
+        path: "**/test-results.trx"                            
         reporter: dotnet-trx
+        fail-on-error: true
 
 
